/* I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
 I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
 ░░░░░▄▄▄▄▀▀▀▀▀▀▀▀▄▄▄▄▄▄░░░░░░░ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
░░░░░█░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░▀▀▄░░░░ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
░░░░█░░░▒▒▒▒▒▒░░░░░░░░▒▒▒░░█░░░ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
░░░█░░░░░░▄██▀▄▄░░░░░▄▄▄░░░░█░░ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
░▄▀▒▄▄▄▒░█▀▀▀▀▄▄█░░░██▄▄█░░░░█░ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
█░▒█▒▄░▀▄▄▄▀░░░░░░░░█░░░▒▒▒▒▒░█ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
█░▒█░█▀▄▄░░░░░█▀░░░░▀▄░░▄▀▀▀▄▒█ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
░█░▀▄░█▄░█▀▄▄░▀░▀▀░▄▄▀░░░░█░░█░ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
░░█░░░▀▄▀█▄▄░█▀▀▀▄▄▄▄▀▀█▀██░█░░ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
░░░█░░░░██░░▀█▄▄▄█▄▄█▄████░█░░░ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
░░░░█░░░░▀▀▄░█░░░█░█▀██████░█░░ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
░░░░░▀▄░░░░░▀▀▄▄▄█▄█▄█▄█▄▀░░█░░ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
░░░░░░░▀▄▄░▒▒▒▒░░░░░░░░░░▒░░░█░ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
░░░░░░░░░░▀▀▄▄░▒▒▒▒▒▒▒▒▒▒░░░░█░ I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO I HATE VISUAL STUDIO
░░░░░░░░░░░░░░▀▄▄▄▄▄░░░░░░░░█░░ WHY CAN'T IT JUST LET ME COMPILE NON SOLUTION FILES LIKE A NORMAL IDE
*/